<!DOCTYPE html>
<html lang="en"><head>
<script src="chapter-slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="chapter-slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="chapter-slides_files/libs/quarto-html/popper.min.js"></script>
<script src="chapter-slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="chapter-slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="chapter-slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="chapter-slides_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="chapter-slides_files/libs/quarto-contrib/fontawesome6-6.7.2/all.min.css" rel="stylesheet">
<link href="chapter-slides_files/libs/quarto-contrib/fontawesome6-6.7.2/latex-fontsize.css" rel="stylesheet">
<script src="chapter-slides_files/libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="chapter-slides_files/libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="chapter-slides_files/libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Russell E. Lewis">
  <meta name="dcterms.date" content="2026-07-20">
  <title>Sulfonamides and Trimethoprim; TMP-SMX</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="chapter-slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="chapter-slides_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="chapter-slides_files/libs/revealjs/dist/theme/quarto-30b9468806e00b78aebc81cf53c5f7db.css">
  <link href="chapter-slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="chapter-slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="chapter-slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="chapter-slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Sulfonamides and Trimethoprim; TMP-SMX</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Russell E. Lewis 
</div>
</div>
</div>

  <p class="date">2026-07-20</p>
</section>
<section id="sulfonamides-and-trimethoprim-tmp-smx" class="slide level2 center" data-background-video="tmp-smx-images/agar.mp4" data-background-video-loop="true" data-background-video-muted="true" data-background-color="#b20e10" data-background-opacity="0.5">
<h2>Sulfonamides and Trimethoprim: TMP-SMX</h2>
<p><br></p>
<center>
<p><strong>Russell E. Lewis, Pharm.D</strong> <br> Associate Professor of Infectious Diseases (MEDS-10/B) <br></p>
<p><br> <br></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><a href="tmp-smx-images/DMM_newlogo.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img data-src="tmp-smx-images/DMM_newlogo.png" class="quarto-figure quarto-figure-center" width="350"></a></p>
</figure>
</div>
<p><br> <i class="fa-solid fa-envelope fa-1x" aria-label="envelope"></i> russelledward.lewis@unipd.it <br> <i class="fa-brands fa-github fa-1x" aria-label="github"></i> <a href="https://github.com/Russlewisbo/ESCMID_2022_talk">https://github.com/Russlewisbo</a> <br> Slides and course materials: <a href="https://padovaid.com/">www.idpadova.com</a></p>
</center></section>
<section id="learning-objectives-1-of-2" class="slide level2 center">
<h2>Learning objectives (1 of 2)</h2>
<p><br></p>
<p>By the end of this lecture, you should be able to:</p>
<ol type="1">
<li>Describe the history and development of sulfonamides</li>
<li>Explain the chemical structure-activity relationships of sulfonamides</li>
<li>Describe the mechanism of action of sulfonamides and trimethoprim</li>
<li>Explain the basis for synergy in TMP-SMX combination</li>
</ol>
</section>
<section id="learning-objectives-2-of-2" class="slide level2 center">
<h2>Learning objectives (2 of 2)</h2>
<p><br></p>
<ol start="5" type="1">
<li>List the major mechanisms of resistance to sulfonamides and trimethoprim</li>
<li>Describe the pharmacokinetics and tissue distribution</li>
<li>Recognize common and serious adverse reactions</li>
<li>Identify appropriate clinical indications for TMP-SMX</li>
<li>Manage drug interactions and special populations</li>
</ol>
</section>
<section>
<section id="part-1-history-and-discovery" class="title-slide slide level1 center" data-background-color="#b20e10">
<h1>PART 1: History and Discovery</h1>

</section>
<section id="the-birth-of-antimicrobial-chemotherapy" class="slide level2 center">
<h2>The birth of antimicrobial chemotherapy</h2>
<p><br></p>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li><strong>1932</strong>: Gerhard Domagk discovers Prontosil</li>
<li>First synthetic antimicrobial agent</li>
<li>German dye industry origin</li>
<li>Protected mice from <em>Streptococcus pyogenes</em></li>
</ul>
</div><div class="column" style="width:40%;">
<p><a href="tmp-smx-images/Domagk.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img data-src="tmp-smx-images/Domagk.png" width="350"></a></p>
</div></div>

<aside><div>
<p>Domagk was working for I.G. Farbenindustrie when he discovered that the red dye Prontosil protected mice from streptococcal infections. He received the Nobel Prize in 1939, though the Nazi regime forced him to decline it initially.</p>
</div></aside></section>
<section id="prontosil-to-sulfanilamide" class="slide level2 center">
<h2>Prontosil to sulfanilamide</h2>
<p><br></p>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Prontosil was a <strong>prodrug</strong></li>
<li>Active metabolite: <strong>sulfanilamide</strong></li>
<li>Released in vivo through azo bond cleavage</li>
<li>First use in US: July 1935
<ul>
<li>10-year-old girl with <em>H. influenzae</em> meningitis</li>
<li>Unfortunately unsuccessful (too late in disease)</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<p><a href="tmp-smx-images/treufel.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img data-src="tmp-smx-images/treufel.png" width="350"></a></p>
</div></div>

<aside><div>
<p>The French team of Tréfouël discovered that the active compound was actually sulfanilamide, not the parent dye. This was important because sulfanilamide couldn’t be patented, leading to widespread availability.</p>
</div></aside></section>
<section id="evolution-of-sulfonamides" class="slide level2 center">
<h2>Evolution of sulfonamides</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Decade</th>
<th>Development</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1930s</td>
<td>Basic sulfanilamide modifications</td>
</tr>
<tr class="even">
<td>1940s</td>
<td>Sulfadiazine for systemic infections</td>
</tr>
<tr class="odd">
<td>1950s</td>
<td>Trimethoprim synthesis (Hitchings)</td>
</tr>
<tr class="even">
<td>1960s</td>
<td>TMP-SMX combination introduced</td>
</tr>
<tr class="odd">
<td>1970s+</td>
<td>Prophylaxis for opportunistic infections</td>
</tr>
</tbody>
</table>
<p><br> <br></p>

<aside><div>
<p>Sulfonamides were the dominant antimicrobials before penicillin became widely available. Even today, in combination with trimethoprim, they remain clinically valuable.</p>
</div></aside></section></section>
<section>
<section id="part-2-sulfonamide-chemistry-and-structure" class="title-slide slide level1 center" data-background-color="#b20e10">
<h1>PART 2: <br> Sulfonamide Chemistry and Structure</h1>

</section>
<section id="sulfonamide-structure-basics" class="slide level2 smaller center">
<h2>Sulfonamide structure basics</h2>
<p><br></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Key structural features:</strong></p>
<ul>
<li>Benzene ring core</li>
<li>Sulfonamide group (-SO₂NH₂)</li>
<li>Free amino group at 4-carbon</li>
<li>Similar to PABA</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><a href="tmp-smx-images/sulfa_structres.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Sulfonamide structures"><img data-src="tmp-smx-images/sulfa_structres.png" alt="Sulfonamide structures"></a></p>
<figcaption>Sulfonamide structures</figcaption>
</figure>
</div>
</div></div>

<aside><div>
<p>The free amino group at the 4-carbon position is essential for activity.The illustration shows the structural formulas of six different sulfonamide compounds labeled A through F. Panel A displays the structure of sulfanilamide, which consists of a benzene ring substituted with å primary amine and å sulfonamide group. Panel B presents para-aminobenzoic acid with carboxylic acid and an amine group in para positions on å benzene ring. Panel illustrates sulfadiazine, containing a sulfanilamide core with a pyrimidine ring attached through å nitrogen-sulfur finkage. Panel D features sulfisoxazole, with the sulfanilamide båse attached to a methyl-substituted isoxazole ring. Panel E shows sulfamethoxazole, where a methoxazole ring is bonded to the sulfanilamide group. Panel F presents sulfathalidine, also called bhthalvisulfathiazole, which contains a sulfanilamide moiety linked to a thiazole ring and a phthalyl group bearina a carboxylic acid.</p>
</div></aside></section>
<section id="structure-activity-relationships" class="slide level2 center">
<h2>Structure-activity relationships</h2>
<p><br></p>
<p><strong>Activity-enhancing modifications:</strong></p>
<ul>
<li>Free 4-amino group → <strong>Essential</strong> for activity</li>
<li>Sulfonyl (SO₂) substitutions → Increased PABA inhibition</li>
<li>Examples: sulfadiazine, sulfisoxazole, sulfamethoxazole</li>
</ul>
<p><strong>Activity-decreasing modifications:</strong></p>
<ul>
<li>N-1 substitutions → Decreased GI absorption</li>
</ul>

<aside><div>
<p>The nature of substitutions determines not only activity but also pharmacokinetic properties like absorption, solubility, and protein binding.</p>
</div></aside></section>
<section id="classification-of-sulfonamides" class="slide level2 center">
<h2>Classification of sulfonamides</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Class</th>
<th>Examples</th>
<th>Key Features</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Short/medium-acting</td>
<td>Sulfisoxazole, SMX</td>
<td>Most common, systemic</td>
</tr>
<tr class="even">
<td>Long-acting</td>
<td>Sulfadoxine</td>
<td>T½ 100-230 hrs, malaria</td>
</tr>
<tr class="odd">
<td>GI-limited</td>
<td>Sulfasalazine</td>
<td>Poorly absorbed, IBD</td>
</tr>
<tr class="even">
<td>Topical</td>
<td>Silver sulfadiazine</td>
<td>Burns, wounds</td>
</tr>
</tbody>
</table>

<aside><div>
<p>This classification is clinically useful. Short-acting agents are the most commonly used. Long-acting agents fell out of favor due to Stevens-Johnson syndrome risk but remain useful for malaria.</p>
</div></aside></section>
<section id="sulfamethoxazole-the-most-important" class="slide level2 center">
<h2>Sulfamethoxazole: The most important</h2>
<p><br></p>
<ul>
<li><em>N’</em>-(5-methyl-3-isoxazolyl) sulfanilamide</li>
<li>Less soluble than sulfisoxazole</li>
<li>Higher blood levels achieved</li>
<li><strong>The sulfonamide in TMP-SMX</strong></li>
<li>Half-life ~11 hours (matches TMP)</li>
</ul>
<p><br> <br></p>

<aside><div>
<p>Sulfamethoxazole was chosen for the TMP combination specifically because its pharmacokinetic profile (particularly half-life) closely matches that of trimethoprim, making it ideal for twice-daily dosing.</p>
</div></aside></section></section>
<section>
<section id="part-3-mechanism-of-action" class="title-slide slide level1 center" data-background-color="#b20e10">
<h1>PART 3: Mechanism of Action</h1>

</section>
<section id="the-folic-acid-pathway" class="slide level2 center">
<h2>The folic acid pathway</h2>
<p><br></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><a href="tmp-smx-images/folicacid.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img data-src="tmp-smx-images/folicacid.png" class="quarto-figure quarto-figure-center" width="800"></a></p>
</figure>
</div>
</section>
<section id="step-1-sulfonamide-action" class="slide level2 center">
<h2>Step 1: Sulfonamide action</h2>
<p><br></p>
<p><strong>Target:</strong> Dihydropteroate synthase (DHPS)</p>
<ul>
<li>Sulfonamides are PABA analogs</li>
<li>Competitive inhibition of PABA incorporation</li>
<li>Can be incorporated into dihydropteroate</li>
<li><strong>Result:</strong> Decreased dihydrofolic acid synthesis</li>
</ul>

<aside><div>
<p>Sulfonamides may actually have higher affinity for DHPS than the natural substrate PABA. They may also be incorporated into abnormal folate intermediates.</p>
</div></aside></section>
<section id="step-2-trimethoprim-action" class="slide level2 center">
<h2>Step 2: Trimethoprim action</h2>
<p><br></p>
<p><strong>Target:</strong> Dihydrofolate reductase (DHFR)</p>
<ul>
<li>Blocks conversion of dihydrofolate → tetrahydrofolate</li>
<li>50,000-100,000x more active against bacterial vs human DHFR</li>
<li><strong>Selective toxicity</strong> is key</li>
<li>Result: Decreased tetrahydrofolic acid</li>
</ul>
<p><br> <br></p>

<aside><div>
<p>The remarkable selectivity of trimethoprim for bacterial DHFR over human DHFR is the basis for its therapeutic index. Human cells obtain folic acid from the diet and don’t require the synthesis pathway.</p>
</div></aside></section>
<section id="sequential-blockade-synergy" class="slide level2 center">
<h2>Sequential blockade = synergy</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<svg width="960" height="480" viewbox="0.00 0.00 806.15 98.00" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none; display: block; margin: auto auto auto auto">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 94)">
<title>folate_pathway</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-94 802.15,-94 802.15,4 -4,4"></polygon>
<!-- PABA -->
<g id="node1" class="node">
<title>PABA</title>
<path fill="white" stroke="black" d="M227.95,-36C227.95,-36 197.95,-36 197.95,-36 191.95,-36 185.95,-30 185.95,-24 185.95,-24 185.95,-12 185.95,-12 185.95,-6 191.95,0 197.95,0 197.95,0 227.95,0 227.95,0 233.95,0 239.95,-6 239.95,-12 239.95,-12 239.95,-24 239.95,-24 239.95,-30 233.95,-36 227.95,-36"></path>
<text text-anchor="middle" x="212.95" y="-13.8" font-family="Helvetica,sans-Serif" font-size="14.00">PABA</text>
</g>
<!-- DHF -->
<g id="node2" class="node">
<title>DHF</title>
<path fill="white" stroke="black" d="M435.31,-63C435.31,-63 340.89,-63 340.89,-63 334.89,-63 328.89,-57 328.89,-51 328.89,-51 328.89,-39 328.89,-39 328.89,-33 334.89,-27 340.89,-27 340.89,-27 435.31,-27 435.31,-27 441.31,-27 447.31,-33 447.31,-39 447.31,-39 447.31,-51 447.31,-51 447.31,-57 441.31,-63 435.31,-63"></path>
<text text-anchor="middle" x="388.1" y="-40.8" font-family="Helvetica,sans-Serif" font-size="14.00">Dihydrofolic acid</text>
</g>
<!-- PABA&#45;&gt;DHF -->
<g id="edge1" class="edge">
<title>PABA-&gt;DHF</title>
<path fill="none" stroke="black" d="M240.25,-22.1C261.06,-25.35 291.1,-30.03 318.59,-34.32"></path>
<polygon fill="black" stroke="black" points="318.16,-37.79 328.58,-35.88 319.24,-30.88 318.16,-37.79"></polygon>
<text text-anchor="middle" x="295.46" y="-35.3" font-family="Helvetica,sans-Serif" font-size="11.00">DHPS</text>
</g>
<!-- THF -->
<g id="node3" class="node">
<title>THF</title>
<path fill="white" stroke="black" d="M640.25,-63C640.25,-63 525.92,-63 525.92,-63 519.92,-63 513.92,-57 513.92,-51 513.92,-51 513.92,-39 513.92,-39 513.92,-33 519.92,-27 525.92,-27 525.92,-27 640.25,-27 640.25,-27 646.25,-27 652.25,-33 652.25,-39 652.25,-39 652.25,-51 652.25,-51 652.25,-57 646.25,-63 640.25,-63"></path>
<text text-anchor="middle" x="583.09" y="-40.8" font-family="Helvetica,sans-Serif" font-size="14.00">Tetrahydrofolic acid</text>
</g>
<!-- DHF&#45;&gt;THF -->
<g id="edge2" class="edge">
<title>DHF-&gt;THF</title>
<path fill="none" stroke="black" d="M447.52,-45C465.2,-45 484.91,-45 503.68,-45"></path>
<polygon fill="black" stroke="black" points="503.68,-48.5 513.68,-45 503.68,-41.5 503.68,-48.5"></polygon>
<text text-anchor="middle" x="480.73" y="-48.3" font-family="Helvetica,sans-Serif" font-size="11.00">DHFR</text>
</g>
<!-- DNA -->
<g id="node4" class="node">
<title>DNA</title>
<path fill="white" stroke="black" d="M786.14,-63C786.14,-63 701.18,-63 701.18,-63 695.18,-63 689.18,-57 689.18,-51 689.18,-51 689.18,-39 689.18,-39 689.18,-33 695.18,-27 701.18,-27 701.18,-27 786.14,-27 786.14,-27 792.14,-27 798.14,-33 798.14,-39 798.14,-39 798.14,-51 798.14,-51 798.14,-57 792.14,-63 786.14,-63"></path>
<text text-anchor="middle" x="743.66" y="-40.8" font-family="Helvetica,sans-Serif" font-size="14.00">Purines + DNA</text>
</g>
<!-- THF&#45;&gt;DNA -->
<g id="edge3" class="edge">
<title>THF-&gt;DNA</title>
<path fill="none" stroke="black" d="M652.26,-45C661.06,-45 670.06,-45 678.8,-45"></path>
<polygon fill="black" stroke="black" points="678.9,-48.5 688.9,-45 678.9,-41.5 678.9,-48.5"></polygon>
</g>
<!-- Sulfonamides -->
<g id="node5" class="node">
<title>Sulfonamides</title>
<path fill="#ffcccc" stroke="black" d="M88.74,-36C88.74,-36 12.09,-36 12.09,-36 6.09,-36 0.09,-30 0.09,-24 0.09,-24 0.09,-12 0.09,-12 0.09,-6 6.09,0 12.09,0 12.09,0 88.74,0 88.74,0 94.74,0 100.74,-6 100.74,-12 100.74,-12 100.74,-24 100.74,-24 100.74,-30 94.74,-36 88.74,-36"></path>
<text text-anchor="middle" x="50.41" y="-13.8" font-family="Helvetica,sans-Serif" font-size="14.00">Sulfonamides</text>
</g>
<!-- Sulfonamides&#45;&gt;PABA -->
<g id="edge4" class="edge">
<title>Sulfonamides-&gt;PABA</title>
<path fill="none" stroke="#cc0000" stroke-dasharray="5,2" d="M100.89,-18C126.82,-18 157.8,-18 180.45,-18"></path>
<polygon fill="#cc0000" stroke="#cc0000" points="184.72,-13 184.72,-23 182.72,-23 182.72,-13 184.72,-13"></polygon>
<polyline fill="none" stroke="#cc0000" points="185.72,-18 180.72,-18 "></polyline>
<text text-anchor="middle" x="132.28" y="-21.3" font-family="Helvetica,sans-Serif" font-size="11.00" fill="#cc0000">Block</text>
</g>
<!-- Trimethoprim -->
<g id="node6" class="node">
<title>Trimethoprim</title>
<path fill="#cce5ff" stroke="black" d="M250.41,-90C250.41,-90 175.5,-90 175.5,-90 169.5,-90 163.5,-84 163.5,-78 163.5,-78 163.5,-66 163.5,-66 163.5,-60 169.5,-54 175.5,-54 175.5,-54 250.41,-54 250.41,-54 256.41,-54 262.41,-60 262.41,-66 262.41,-66 262.41,-78 262.41,-78 262.41,-84 256.41,-90 250.41,-90"></path>
<text text-anchor="middle" x="212.95" y="-67.8" font-family="Helvetica,sans-Serif" font-size="14.00">Trimethoprim</text>
</g>
<!-- Trimethoprim&#45;&gt;DHF -->
<g id="edge5" class="edge">
<title>Trimethoprim-&gt;DHF</title>
<path fill="none" stroke="#cc0000" stroke-dasharray="5,2" d="M262.18,-64.48C281.19,-61.52 303.28,-58.07 323.55,-54.91"></path>
<polygon fill="#cc0000" stroke="#cc0000" points="326.9,-49.33 328.45,-59.21 326.47,-59.51 324.93,-49.63 326.9,-49.33"></polygon>
<polyline fill="none" stroke="#cc0000" points="328.66,-54.11 323.72,-54.88 "></polyline>
<text text-anchor="middle" x="295.46" y="-63.3" font-family="Helvetica,sans-Serif" font-size="11.00" fill="#cc0000">Block</text>
</g>
</g>
</svg>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>

<aside><div>
<p>Why synergy occurs: Dual pathway blockade, bacteriostatic → Bactericidal effect, reduced resistance emergence</p>
</div></aside></section>
<section id="key-concept-bacteriostatic-vs-bactericidal" class="slide level2 center">
<h2>Key concept: Bacteriostatic vs bactericidal</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Property</th>
<th style="text-align: center;">Sulfonamide Alone</th>
<th style="text-align: center;">TMP Alone</th>
<th style="text-align: center;">TMP-SMX</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Effect</td>
<td style="text-align: center;">Bacteriostatic</td>
<td style="text-align: center;">Bacteriostatic</td>
<td style="text-align: center;"><strong>Bactericidal</strong></td>
</tr>
<tr class="even">
<td>Inhibition</td>
<td style="text-align: center;">DHPS</td>
<td style="text-align: center;">DHFR</td>
<td style="text-align: center;">Both</td>
</tr>
<tr class="odd">
<td>Resistance</td>
<td style="text-align: center;">Higher risk</td>
<td style="text-align: center;">Higher risk</td>
<td style="text-align: center;">Lower risk</td>
</tr>
</tbody>
</table>
<p><br></p>

<aside><div>
<p>The synergistic combination achieves bactericidal activity against many organisms that either agent alone would only inhibit. This is clinically relevant for serious infections.</p>
</div></aside></section>
<section id="why-humans-are-spared" class="slide level2 center">
<h2>Why humans are spared</h2>
<p><br></p>
<p><strong>Selective toxicity explained:</strong></p>
<ol type="1">
<li>Humans cannot synthesize folic acid</li>
<li>Humans obtain folate from diet</li>
<li>Human DHFR has very low affinity for TMP</li>
<li>Mammalian cells take up preformed folate</li>
</ol>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>High doses or prolonged therapy can still cause folate deficiency - supplement with leucovorin when needed</p>
</div>
</div>
</div>

<aside><div>
<p>This is why TMP-SMX is generally well-tolerated despite blocking such fundamental metabolic pathways. However, prolonged high-dose therapy can deplete folate stores, especially in malnourished patients.</p>
</div></aside></section></section>
<section>
<section id="part-4-antimicrobial-spectrum-and-resistance" class="title-slide slide level1 center" data-background-color="#b20e10">
<h1>PART 4: Antimicrobial Spectrum and Resistance</h1>

</section>
<section id="spectrum-of-activity" class="slide level2 center">
<h2>Spectrum of activity</h2>
<p><br></p>
<p><strong>Gram-positive:</strong></p>
<ul>
<li><em>S. aureus</em> (including many CA-MRSA)</li>
<li><em>S. pneumoniae</em> (resistance increasing)</li>
<li>Group A, B <em>Streptococci</em> (classically throught to be resistant-artifact of thymidine in test medium)</li>
<li><em>Listeria monocytogenes</em></li>
<li><em>Nocardia</em> species</li>
</ul>
<p><strong>Gram-negative:</strong></p>
<ul>
<li>Most <em>Enterobacterales</em></li>
<li><em>H. influenzae</em></li>
<li><em>Stenotrophomonas maltophilia</em></li>
<li>NOT <em>Pseudomonas aeruginosa</em></li>
</ul>

<aside><div>
<p>TMP-SMX has an impressively broad spectrum. Notable gaps include Pseudomonas and most anaerobes. The activity against MRSA and Stenotrophomonas is particularly valuable clinically.</p>
</div></aside></section>
<section id="activity-against-special-pathogens" class="slide level2 center">
<h2>Activity against special pathogens</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Organism</th>
<th style="text-align: center;">Activity</th>
<th>Clinical Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Pneumocystis jirovecii</em></td>
<td style="text-align: center;">+++</td>
<td>First-line</td>
</tr>
<tr class="even">
<td><em>Toxoplasma gondii</em></td>
<td style="text-align: center;">++</td>
<td>Alternative</td>
</tr>
<tr class="odd">
<td><em>Nocardia</em> spp.</td>
<td style="text-align: center;">+++</td>
<td>First-line</td>
</tr>
<tr class="even">
<td><em>Stenotrophomonas</em></td>
<td style="text-align: center;">+++</td>
<td>First-line</td>
</tr>
<tr class="odd">
<td><em>Isospora/Cyclospora</em></td>
<td style="text-align: center;">+++</td>
<td>First-line</td>
</tr>
</tbody>
</table>

<aside><div>
<p>These special pathogens are where TMP-SMX really shines. For PCP and Nocardia, it’s the drug of choice. For Stenotrophomonas, it’s often the only oral option.</p>
</div></aside></section>
<section id="resistance-the-growing-problem" class="slide level2 center">
<h2>Resistance: The growing problem</h2>
<p><br></p>
<p><strong>Resistance rates are increasing:</strong></p>
<ul>
<li><em>E. coli</em> (UTI isolates): 20-30% resistant in many areas</li>
<li><em>S. pneumoniae</em>: 25-50% resistant globally</li>
<li><em>Shigella</em>: &gt;30% resistant in US, &gt;75% in China</li>
<li><em>Salmonella</em>: Majority of isolates now resistant</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Always check local resistance patterns before empiric therapy!</p>
</div>
</div>
</div>

<aside><div>
<p>The once-reliable activity of TMP-SMX against common pathogens is being eroded by resistance. This is why it’s no longer first-line for many UTIs in high-resistance areas.</p>
</div></aside></section>
<section id="mechanisms-of-resistance-sulfonamides" class="slide level2 center">
<h2>Mechanisms of resistance-sulfonamides</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><a href="tmp-smx-images/sulfa_r.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img data-src="tmp-smx-images/sulfa_r.png" class="quarto-figure quarto-figure-center" width="800"></a></p>
</figure>
</div>

<aside><div>
<p>Multiple mechanisms can operate simultaneously. The sul genes are particularly concerning as they’re often carried on mobile genetic elements like integrons.</p>
</div></aside></section>
<section id="mechanisms-of-resistance-trimethoprim-continued" class="slide level2 center">
<h2>Mechanisms of resistance-trimethoprim (continued)</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><a href="tmp-smx-images/tmp_R.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img data-src="tmp-smx-images/tmp_R.png" class="quarto-figure quarto-figure-center" width="800"></a></p>
</figure>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Cross-resistance between sulfonamides is common; resistance to one = resistance to all</p>
</div>
</div>
</div>

<aside><div>
<p>The large number of dfr gene variants (over 30 identified) reflects the strong selective pressure that has been applied to these drugs over decades of use.</p>
</div></aside></section></section>
<section>
<section id="part-5-pharmacology" class="title-slide slide level1 center" data-background-color="#b20e10">
<h1>PART 5: Pharmacology</h1>

</section>
<section id="pharmacokinetics-overview" class="slide level2 center">
<h2>Pharmacokinetics overview</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parameter</th>
<th style="text-align: center;">TMP</th>
<th style="text-align: center;">SMX</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bioavailability</td>
<td style="text-align: center;">&gt;90%</td>
<td style="text-align: center;">&gt;90%</td>
</tr>
<tr class="even">
<td>T<sub>max</sub></td>
<td style="text-align: center;">1-4 hr</td>
<td style="text-align: center;">1-4 hr</td>
</tr>
<tr class="odd">
<td>Half-life</td>
<td style="text-align: center;">8-10 hr</td>
<td style="text-align: center;">9-11 hr</td>
</tr>
<tr class="even">
<td>Protein binding</td>
<td style="text-align: center;">45%</td>
<td style="text-align: center;">70%</td>
</tr>
<tr class="odd">
<td>CSF penetration</td>
<td style="text-align: center;">40-50%</td>
<td style="text-align: center;">25-50%</td>
</tr>
</tbody>
</table>
<p><br></p>

<aside><div>
<p>The matched pharmacokinetics of TMP and SMX make them ideal combination partners. Both have excellent oral bioavailability and penetrate well into tissues.</p>
</div></aside></section>
<section id="the-magic-of-the-15-ratio" class="slide level2 center">
<h2>The magic of the 1:5 ratio</h2>
<p><br></p>
<p><strong>Fixed-dose combination:</strong></p>
<ul>
<li>TMP 160 mg + SMX 800 mg = <strong>DS tablet</strong></li>
<li>Produces serum ratio ~1:20</li>
<li>Optimal for synergy against most pathogens</li>
</ul>
<p><strong>Why this ratio?</strong></p>
<ul>
<li>Accounts for different protein binding</li>
<li>Accounts for different tissue distribution</li>
<li>Maximizes bactericidal synergy</li>
</ul>

<aside><div>
<p>The 1:5 ratio in the tablet produces approximately a 1:20 ratio in serum due to the different protein binding and distribution characteristics. This was carefully optimized in early clinical trials.</p>
</div></aside></section>
<section id="iv-to-oral-conversion-formulations" class="slide level2 smaller center">
<h2>IV to oral conversion &amp; formulations</h2>
<p><br></p>
<p><strong>~90-100% oral bioavailability → convert IV to PO 1:1</strong> (based on TMP)</p>
<table class="caption-top">
<colgroup>
<col style="width: 38%">
<col style="width: 30%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Formulation (EU / Italy)</th>
<th style="text-align: center;">TMP + SMX per unit</th>
<th>Common label / pack</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>IV infusion (<em>fiala</em>)</td>
<td style="text-align: center;">16/80 mg per mL; 5 mL ampoule = 80/400</td>
<td>“480 mg”</td>
</tr>
<tr class="even">
<td>Tablet — standard (<em>compresse</em>)</td>
<td style="text-align: center;">160/800 mg</td>
<td>“Bactrim forte” / 960 mg</td>
</tr>
<tr class="odd">
<td>Tablet — single strength</td>
<td style="text-align: center;">80/400 mg</td>
<td>“480 mg”</td>
</tr>
<tr class="even">
<td>Oral suspension (Italy)</td>
<td style="text-align: center;">80/400 mg per 5 mL</td>
<td>100 mL bottle</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>Convert when:</strong> tolerating oral intake, hemodynamically stable, GI absorption intact</p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Always dose by the TMP component</strong></p>
</div>
<div class="callout-content">
<p>TMP is the dose-limiting, dose-defining moiety. Prescribe and calculate mg/kg on <strong>TMP</strong>, not the combined product or the SMX. e.g.&nbsp;15 mg/kg/day TMP for severe infections, divided q6-8h — the SMX follows the fixed 1:5 ratio.</p>
</div>
</div>
</div>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>EU vs US labelling trap:</strong> European/Italian products are labelled by the <strong>combined</strong> amount (“480 mg” = 80 TMP + 400 SMX), while US references dose by <strong>TMP alone</strong>. Always specify the TMP dose to avoid 5-fold errors.</p>
</div>
</div>
</div>
</section>
<section id="worked-example-dosing-by-tmp" class="slide level2 smaller center">
<h2>Worked example: dosing by TMP</h2>
<p><br></p>
<p><strong>70 kg patient, <em>Stenotrophomonas maltophilia</em> pneumonia, normal renal function</strong></p>
<ol type="1">
<li>Choose target: <strong>10 mg/kg/day of TMP</strong> → 70 × 10 = <strong>700 mg TMP/day</strong></li>
<li>Divide q8h → ≈ <strong>240 mg TMP per dose</strong> (700 ÷ 3, rounded to whole ampoules)</li>
<li>Express in product units:</li>
</ol>
<table class="caption-top">
<thead>
<tr class="header">
<th>Route</th>
<th>Per dose (q8h)</th>
<th>In “480 mg” units</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>IV</td>
<td>3 ampoules (3 × 80 = 240 mg TMP)</td>
<td>3 × 480 mg = 1440 mg</td>
</tr>
<tr class="even">
<td>PO</td>
<td>1.5 standard tablets (160 mg TMP each)</td>
<td>1.5 × 960 mg</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>Oral step-down uses the <strong>same TMP dose</strong> — no reduction for the switch.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Note how the <em>same</em> regimen reads as “240 mg TMP q8h” (US style) or “1440 mg co-trimoxazole q8h” (EU style). Anchor on the TMP number and the two never conflict.</p>
</div>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Per il contesto italiano</strong></p>
</div>
<div class="callout-content">
<p>La scheda tecnica italiana (<em>Bactrim perfusione</em>) esprime la posologia sul <strong>totale</strong> cotrimossazolo, tipicamente come mg/kg di entrambi i componenti (es. 20 mg/kg/die di trimetoprim + 100 mg/kg/die di sulfametossazolo, in 3–4 <em>fiale</em> ogni 6 ore). In reparto ordinate in <em>fiale</em> da “480 mg” (80 mg TMP), ma <strong>calcolate e verificate sempre la dose sul trimetoprim</strong> per evitare errori di un fattore 5.</p>
</div>
</div>
</div>
</section>
<section id="tissue-distribution" class="slide level2 center">
<h2>Tissue distribution</h2>
<p><br></p>
<p><strong>Excellent penetration into:</strong></p>
<ul>
<li>Cerebrospinal fluid (40-50%)</li>
<li>Prostatic tissue</li>
<li>Respiratory secretions</li>
<li>Middle ear fluid</li>
<li>Synovial fluid</li>
<li>Pleural and peritoneal fluids</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Good CNS penetration makes TMP-SMX useful for: - Toxoplasmic encephalitis - Nocardia brain abscess</p>
</div>
</div>
</div>

<aside><div>
<p>The good tissue penetration, especially into CSF, is a major advantage. Many antibiotics do not penetrate the CNS well, limiting their usefulness for these serious infections.</p>
</div></aside></section>
<section id="metabolism-and-elimination" class="slide level2 center">
<h2>Metabolism and elimination</h2>
<p><br></p>
<p><strong>Trimethoprim:</strong></p>
<ul>
<li>50-70% excreted unchanged in urine</li>
<li>Hepatic metabolism (minor)</li>
<li>Active tubular secretion</li>
</ul>
<p><strong>Sulfamethoxazole:</strong></p>
<ul>
<li>Hepatic acetylation and glucuronidation</li>
<li>15-30% excreted unchanged in urine</li>
<li>Metabolized by CYP2C9</li>
</ul>

<aside><div>
<p>Both components have significant renal excretion, which is why dose adjustment is needed in renal impairment. The high urinary concentrations also explain the effectiveness for UTIs.</p>
</div></aside></section>
<section id="renal-dosing-adjustments" class="slide level2 center">
<h2>Renal dosing adjustments</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">CrCl (mL/min)</th>
<th>Dose Adjustment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">&gt;30</td>
<td>Full dose</td>
</tr>
<tr class="even">
<td style="text-align: center;">15-30</td>
<td>50% reduction</td>
</tr>
<tr class="odd">
<td style="text-align: center;">&lt;15</td>
<td>Avoid (or 50% q24h with monitoring)</td>
</tr>
</tbody>
</table>
<p><strong>Hemodialysis:</strong> Give dose after dialysis</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Monitor creatinine closely - TMP can increase serum creatinine by blocking tubular secretion (not true nephrotoxicity)</p>
</div>
</div>
</div>

<aside><div>
<p>The creatinine increase from TMP is a pharmacokinetic effect, not true nephrotoxicity. TMP blocks the tubular secretion of creatinine, raising serum levels without affecting true GFR. However, actual nephrotoxicity (interstitial nephritis) can also occur.</p>
</div></aside></section></section>
<section>
<section id="part-6-adverse-effects" class="title-slide slide level1 center" data-background-color="#b20e10">
<h1>PART 6: Adverse Effects</h1>

</section>
<section id="common-adverse-effects" class="slide level2 center">
<h2>Common adverse effects</h2>
<p><br></p>
<p><strong>Gastrointestinal (most common):</strong></p>
<ul>
<li>Nausea, vomiting</li>
<li>Anorexia</li>
<li>Diarrhea</li>
</ul>
<p><strong>Dermatologic:</strong></p>
<ul>
<li>Rash (3-5% general population)</li>
<li>Much higher in HIV (50-60%)</li>
<li>Usually maculopapular</li>
</ul>

<p><br></p>
<aside><div>
<p>GI side effects are the most common reason for discontinuation in clinical practice. Taking with food may help. The dramatically higher reaction rate in HIV patients is important to anticipate.</p>
</div></aside></section>
<section id="life-threatening-reactions" class="slide level2 center">
<h2>Life-threatening reactions</h2>
<p><br></p>
<ol type="1">
<li><strong>Stevens-Johnson Syndrome / TEN</strong>
<ul>
<li>Mortality up to 30-40% for TEN</li>
<li>Usually within first 8 weeks</li>
</ul></li>
<li><strong>Severe hematologic toxicity</strong>
<ul>
<li>Agranulocytosis</li>
<li>Aplastic anemia</li>
<li>Thrombocytopenia</li>
</ul></li>
<li><strong>Anaphylaxis</strong></li>
</ol>

<aside><div>
<p>SJS/TEN is the most feared complication. Risk factors include HIV infection and certain HLA types. If a patient develops a severe rash, stop the drug immediately and never rechallenge.</p>
</div></aside></section>
<section id="hyperkalemia-an-underappreciated-risk" class="slide level2 center">
<h2>Hyperkalemia: An underappreciated risk</h2>
<p><br></p>
<p><strong>Mechanism:</strong></p>
<ul>
<li>TMP blocks ENaC sodium channel</li>
<li>Acts like potassium-sparing diuretic</li>
<li>Occurs at therapeutic doses</li>
</ul>
<p><strong>Risk factors:</strong></p>
<ul>
<li>Renal insufficiency</li>
<li>Age &gt;65 years</li>
<li>ACE inhibitors or ARBs</li>
<li>Higher TMP doses</li>
<li>Diabetes mellitus</li>
</ul>

<aside><div>
<p>Hyperkalemia from TMP-SMX is more common than many clinicians realize. Multiple studies have shown increased sudden death risk in patients on ACEi/ARBs who receive TMP-SMX, likely due to hyperkalemia.</p>
</div></aside></section>
<section id="hyperkalemia-management" class="slide level2 center">
<h2>Hyperkalemia management</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Potassium Level</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">&lt;5.5 mEq/L</td>
<td>Monitor</td>
</tr>
<tr class="even">
<td style="text-align: center;">5.5-6.0 mEq/L</td>
<td>Recheck, consider dose reduction</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6.0-6.5 mEq/L</td>
<td>Stop TMP-SMX, dietary K+ restriction</td>
</tr>
<tr class="even">
<td style="text-align: center;">&gt;6.5 mEq/L</td>
<td>Aggressive treatment, alternative antibiotic</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Check potassium within first week in high-risk patients!</p>
</div>
</div>
</div>

<aside><div>
<p>Routine potassium monitoring is especially important in patients on ACE inhibitors, ARBs, or with renal impairment. Most cases of significant hyperkalemia occur within the first 7-10 days.</p>
</div></aside></section>
<section id="hematologic-toxicity" class="slide level2 center">
<h2>Hematologic toxicity</h2>
<p><br></p>
<p><strong>Folate-related:</strong></p>
<ul>
<li>Megaloblastic anemia</li>
<li>Leukopenia</li>
<li>Thrombocytopenia</li>
<li>Risk increases with duration</li>
</ul>
<p><strong>Prevention:</strong></p>
<ul>
<li>Supplemental leucovorin (folinic acid) for high-dose/prolonged therapy</li>
<li>Especially important in malnourished patients</li>
</ul>

<aside><div>
<p>The hematologic effects are related to folate depletion. They’re usually reversible with drug discontinuation. Leucovorin can bypass the folate synthesis block without reducing antibacterial efficacy.</p>
</div></aside></section>
<section id="special-population-hiv-patients" class="slide level2 center">
<h2>Special population: HIV patients</h2>
<p><br></p>
<p><strong>Much higher adverse reaction rates:</strong></p>
<ul>
<li>Rash: 50-60% (vs 3-5%)</li>
<li>Fever common</li>
<li>Often occurs after 1-2 weeks</li>
<li>May tolerate rechallenge or desensitization</li>
</ul>
<p><strong>Despite reactions, TMP-SMX remains:</strong></p>
<ul>
<li>First-line PCP prophylaxis</li>
<li>First-line PCP treatment</li>
<li>Benefits outweigh risks</li>
</ul>

<aside><div>
<p>The high reaction rate in HIV patients was noted early in the AIDS epidemic. The mechanism is unclear but may relate to altered drug metabolism, immune dysregulation, or increased oxidative stress.</p>
</div></aside></section>
<section id="pregnancy-considerations" class="slide level2 center">
<h2>Pregnancy considerations</h2>
<p><br></p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Avoid in late pregnancy</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Sulfonamides compete for bilirubin binding sites</li>
<li>Risk of neonatal hyperbilirubinemia</li>
<li><strong>Kernicterus risk</strong> in newborn</li>
<li>Also avoid in breastfeeding</li>
</ul>
</div>
</div>
</div>
<p><strong>First trimester:</strong></p>
<ul>
<li>Some studies suggest neural tube defect risk</li>
<li>Consider folate supplementation if used</li>
</ul>

<aside><div>
<p>The kernicterus risk is specific to the neonatal period when the blood-brain barrier is immature and bilirubin encephalopathy can occur. TMP-SMX should be avoided after 32 weeks of pregnancy.</p>
</div></aside></section></section>
<section>
<section id="part-7-drug-interactions" class="title-slide slide level1 center" data-background-color="#b20e10">
<h1>PART 7: Drug Interactions</h1>

</section>
<section id="major-drug-interactions" class="slide level2 center">
<h2>Major drug interactions</h2>
<p><br></p>
<table class="caption-top">
<colgroup>
<col style="width: 21%">
<col style="width: 22%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Drug</th>
<th>Effect</th>
<th>Mechanism</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Warfarin</td>
<td>↑ INR</td>
<td>CYP2C9 inhibition</td>
</tr>
<tr class="even">
<td>Methotrexate</td>
<td>↑ Toxicity</td>
<td>Protein displacement, DHFR inhibition</td>
</tr>
<tr class="odd">
<td>Phenytoin</td>
<td>↑ Levels</td>
<td>CYP2C9 inhibition</td>
</tr>
<tr class="even">
<td>Sulfonylureas</td>
<td>↑ Hypoglycemia</td>
<td>Protein displacement</td>
</tr>
</tbody>
</table>

<aside><div>
<p>The warfarin interaction is probably the most clinically important. Always reduce warfarin dose when starting TMP-SMX and monitor INR closely.</p>
</div></aside></section>
<section id="drug-interactions-continued" class="slide level2 center">
<h2>Drug interactions (continued)</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Drug</th>
<th>Effect</th>
<th>Management</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ACEi/ARBs</td>
<td>↑ Hyperkalemia</td>
<td>Monitor K+</td>
</tr>
<tr class="even">
<td>Dofetilide</td>
<td>↑ QT prolongation</td>
<td><strong>Contraindicated</strong></td>
</tr>
<tr class="odd">
<td>Cyclosporine</td>
<td>↓ Levels</td>
<td>Monitor</td>
</tr>
<tr class="even">
<td>Digoxin</td>
<td>↑ Levels</td>
<td>Monitor</td>
</tr>
</tbody>
</table>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>TMP-SMX + Dofetilide = <strong>Absolute contraindication</strong></p>
</div>
</div>
</div>

<aside><div>
<p>Dofetilide is eliminated by renal cation transporters that TMP inhibits, leading to dangerous accumulation and QT prolongation. This is a hard contraindication.</p>
</div></aside></section></section>
<section>
<section id="part-8-clinical-applications" class="title-slide slide level1 center" data-background-color="#b20e10">
<h1>PART 8: Clinical Applications</h1>

</section>
<section id="pcp-the-most-important-indication" class="slide level2 center">
<h2>PCP: The most important indication</h2>
<p><br></p>
<p><strong>Pneumocystis jirovecii Pneumonia:</strong></p>
<ul>
<li><strong>Treatment:</strong> 15-20 mg/kg/day TMP, 21 days</li>
<li><strong>Prophylaxis:</strong> 1 DS tablet daily (or 3x/week)</li>
<li>First-line for both</li>
<li>Add steroids if PaO₂ &lt;70 mmHg</li>
</ul>
<p><strong>Prophylaxis indications:</strong></p>
<ul>
<li>HIV with CD4 &lt;200 cells/µL</li>
<li>Other immunocompromising conditions</li>
<li>Solid organ transplant recipients</li>
</ul>

<aside><div>
<p>TMP-SMX prophylaxis dramatically reduced PCP mortality in the HIV epidemic. Today it remains essential for immunocompromised patients. The 3x weekly dosing is often better tolerated with similar efficacy.</p>
</div></aside></section>
<section id="urinary-tract-infections" class="slide level2 center">
<h2>Urinary tract infections</h2>
<p><br></p>
<p><strong>Uncomplicated cystitis:</strong></p>
<ul>
<li>1 DS tablet BID × 3 days</li>
<li><strong>Only if local resistance &lt;20%</strong></li>
</ul>
<p><strong>Pyelonephritis:</strong></p>
<ul>
<li>1 DS tablet BID × 7-14 days</li>
<li>If susceptible</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Check your local antibiogram! Many areas now have E. coli resistance &gt;20%</p>
</div>
</div>
</div>

<aside><div>
<p>TMP-SMX was once first-line for UTIs everywhere. Now, due to resistance, IDSA guidelines recommend it only in areas where resistance remains below 20%. Fluoroquinolones or nitrofurantoin/fosfomycin may be preferred.</p>
</div></aside></section>
<section id="skin-and-soft-tissue-infections" class="slide level2 center">
<h2>Skin and soft tissue infections</h2>
<p><br></p>
<p><strong>Community-acquired MRSA:</strong></p>
<ul>
<li>TMP-SMX has good CA-MRSA activity</li>
<li>1-2 DS tablets BID × 5-10 days</li>
<li>Often combined with I&amp;D for abscesses</li>
<li>Useful oral step-down option</li>
</ul>
<p><strong>Advantages:</strong></p>
<ul>
<li>Oral bioavailability</li>
<li>Good tissue penetration</li>
<li>Often susceptible when other agents fail</li>
</ul>

<aside><div>
<p>TMP-SMX has become a key agent for CA-MRSA skin infections because it’s oral, well-tolerated, and usually effective.</p>
</div></aside></section>
<section id="the-myth-about-tmpsmx-and-lack-of-activity-against-streptococci" class="slide level2 center">
<h2>The myth about TMP/SMX and lack of activity against Streptococci</h2>
<p><br></p>
<ul>
<li><p>The key issue was thymidine in culture media.</p></li>
<li><p>Streptococci can utilize exogenous thymidine.</p>
<ul>
<li><p>Early susceptibility media often contained relatively high thymidine concentrations.</p></li>
<li><p>Because TMP/SMX inhibits tetrahydrofolate-dependent thymidylate synthesis, providing thymidine externally bypasses the drug’s mechanism.</p></li>
</ul></li>
<li><p><strong>The result was falsely elevated MICs and apparent resistance.</strong></p></li>
<li><p>Modern CLSI-recommended media contain low thymidine concentrations (or thymidine phosphorylase is added), largely eliminating this artifact.</p></li>
</ul>
</section>
<section id="how-do-appropriate-test-conditions-of-tmpsmx-impact-streptococcus-susceptibility" class="slide level2 center">
<h2>How do “appropriate” test conditions of TMP/SMX impact Streptococcus susceptibility?</h2>
<p><br></p>
<p><strong>Most isolates of:</strong></p>
<ul>
<li>Streptococcus pyogenes (Group A Streptococcus)</li>
<li>Streptococcus agalactiae (Group B Streptococcus) many β-hemolytic streptococci</li>
</ul>
<p>…are actually <strong>susceptible in vitro when tested appropriately.</strong></p>
</section>
<section id="nocardiosis" class="slide level2 center">
<h2>Nocardiosis</h2>
<p><br></p>
<p><strong>First-line therapy:</strong></p>
<div>
<ul>
<li>TMP-SMX preferred</li>
<li>High doses: 15-20 mg/kg/day TMP</li>
<li>Duration: 6-12 months (or longer)</li>
<li>May combine with other agents for severe disease</li>
</ul>
</div>
<p><strong>Alternative:</strong> Imipenem, amikacin, linezolid</p>

<aside><div>
<p>Nocardiosis requires prolonged therapy due to the organism’s slow growth. For CNS disease, even longer courses may be needed. TMP-SMX penetrates well into brain abscesses.</p>
</div></aside></section>
<section id="stenotrophomonas-maltophilia" class="slide level2 center">
<h2>Stenotrophomonas maltophilia</h2>
<p><br></p>
<p><strong>Often the only oral option:</strong></p>
<ul>
<li>Intrinsic multidrug resistance</li>
<li>TMP-SMX usually active</li>
<li>Ceftazidime-avibactam + aztreonam or cefidericol may be preferrable in some populations</li>
<li>Important for step-down therapy</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Think about <em>Stenotrophomonas</em> in: - ICU patients on broad-spectrum antibiotics - Ventilator-associated pneumonia - Malignancy patients</p>
</div>
</div>
</div>

<aside><div>
<p>Stenotrophomonas is notoriously resistant to carbapenems and many other agents. TMP-SMX activity is a major advantage, especially for converting IV therapy to an oral option.</p>
</div></aside></section>
<section id="stenotrophomonas-dosing-the-combination-therapy-shift" class="slide level2 smaller center">
<h2>Stenotrophomonas: dosing &amp; the combination-therapy shift</h2>
<p><br></p>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Current dosing (non-cystitis)</strong></p>
<ul>
<li><strong>8–12 mg/kg/day</strong> TMP, divided q8–12h</li>
<li>Consider a <strong>max of ~960 mg/day</strong> TMP</li>
<li>Cystitis: lower doses acceptable (high urinary levels)</li>
</ul>
<p><strong>The recent shift</strong> <span class="citation" data-cites="Tamma2024">(<a href="#/references" role="doc-biblioref" onclick="">Tamma et al. 2024</a>)</span></p>
<ul>
<li>IDSA guidance now favors TMP-SMX <strong>as part of combination therapy</strong>, at least until clinical improvement</li>
<li>Reflects doubt that an “S” on the report predicts monotherapy success</li>
</ul>
</div><div class="column" style="width:45%;">
<p><strong>Why the caution?</strong> <span class="citation" data-cites="Lasko2022">(<a href="#/references" role="doc-biblioref" onclick="">Lasko et al. 2022</a>)</span></p>
<ul>
<li>Breakpoints largely <strong>inherited</strong> from other species</li>
<li>In vitro PK/PD: even ~20 mg/kg/day TMP failed to achieve stasis; up to the equivalent of 100 mg/kg/day could not reach 1-log kill</li>
<li>Derived <strong>free AUC/MIC stasis target ≈ 67</strong> — pushing the dose does not improve target attainment</li>
<li>Murine models poorly translational (high rodent thymidine)</li>
</ul>
</div></div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>First ask: <strong>colonizer or true pathogen?</strong> Steno agents are limited and often poorly tolerated — avoid treating culture results rather than disease.</p>
</div>
</div>
</div>

<aside><div>
<p>Clinical data are heavily confounded (“die <em>from</em> vs <em>with</em> steno”), mostly retrospective, frequently without MICs, and usually involve combination therapy — so monotherapy efficacy remains uncertain. Alternatives (e.g.&nbsp;levofloxacin, cefiderocol, ceftazidime-avibactam plus aztreonam) are also imperfect, making this a genuinely difficult treatment landscape.</p>
</div></aside></section>
<section id="other-clinical-uses" class="slide level2 center">
<h2>Other clinical uses</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Infection</th>
<th>Dose</th>
<th>Duration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Toxoplasmosis</td>
<td>High-dose</td>
<td>6+ weeks</td>
</tr>
<tr class="even">
<td>Traveler’s diarrhea</td>
<td>1 DS BID</td>
<td>3-5 days</td>
</tr>
<tr class="odd">
<td>Isosporiasis</td>
<td>1 DS QID</td>
<td>10 days</td>
</tr>
<tr class="even">
<td>Cyclosporiasis</td>
<td>1 DS BID</td>
<td>7-10 days</td>
</tr>
<tr class="odd">
<td>Listeria meningitis</td>
<td>High-dose IV</td>
<td>3+ weeks</td>
</tr>
</tbody>
</table>

<aside><div>
<p>TMP-SMX remains useful for a variety of infections beyond the major indications. For listeria, it’s an important alternative for penicillin-allergic patients.</p>
</div></aside></section></section>
<section>
<section id="part-9-practical-prescribing" class="title-slide slide level1 center" data-background-color="#b20e10">
<h1>PART 9: Practical Prescribing</h1>

</section>
<section id="dosing-summary" class="slide level2 center">
<h2>Dosing summary</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Indication</th>
<th>Dose</th>
<th>Frequency</th>
<th>Duration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PCP prophylaxis</td>
<td>1 DS</td>
<td>Daily or 3x/wk</td>
<td>Indefinite</td>
</tr>
<tr class="even">
<td>PCP treatment</td>
<td>15-20 mg/kg TMP</td>
<td>Q6-8h</td>
<td>21 days</td>
</tr>
<tr class="odd">
<td>Uncomplicated UTI</td>
<td>1 DS</td>
<td>BID</td>
<td>3 days</td>
</tr>
<tr class="even">
<td>SSTI</td>
<td>1-2 DS</td>
<td>BID</td>
<td>5-10 days</td>
</tr>
<tr class="odd">
<td>Nocardiosis</td>
<td>15 mg/kg TMP</td>
<td>Divided</td>
<td>6-12 mo</td>
</tr>
</tbody>
</table>

<aside><div>
<p>This table provides a quick reference for common dosing regimens. Remember to adjust for renal function and monitor for adverse effects, especially with prolonged use.</p>
</div></aside></section>
<section id="optimizing-the-dose-principles" class="slide level2 smaller center">
<h2>Optimizing the dose: principles</h2>
<p><br></p>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Dose the trimethoprim component</strong></p>
<ul>
<li>Fixed 1:5 TMP:SMX ratio for all formulations</li>
<li>Express dose as <strong>mg/kg/day of TMP</strong></li>
<li>SS = 80 mg TMP; DS = 160 mg TMP</li>
</ul>
<p><strong>Indication drives the target</strong></p>
<ul>
<li>GN bacteremia (step-down): ~5 mg/kg q12h</li>
<li>CA-MRSA SSTI: ~5 mg/kg/day (1 DS BID most)</li>
<li>Bone/joint: ~10 mg/kg/day</li>
<li>PCP treatment: 15–20 mg/kg/day</li>
</ul>
</div><div class="column" style="width:45%;">
<p><strong>Why “optimal” is hard</strong></p>
<ul>
<li>No validated PK/PD index (unlike vanco AUC/MIC)</li>
<li>Legacy targets extrapolated from 1970s–90s data</li>
<li>Emerging PK data suggest lower PCP doses (&lt;10 mg/kg/day) may retain efficacy with fewer ADEs <span class="citation" data-cites="ButlerLaporte2020">(<a href="#/references" role="doc-biblioref" onclick="">Butler-Laporte et al. 2020</a>)</span></li>
<li>IV formulation adds large fluid/D5W burden</li>
</ul>
</div></div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Give an <strong>actual mg dose</strong> using the patient’s real weight rather than a weight-based formula — reduces transcription and math errors. Use the <strong>lowest effective dose</strong> and get creative with split dosing/timing with meals to improve tolerability.</p>
</div>
</div>
</div>

<aside><div>
<p>Dosing schemes vary enormously by indication (a few tablets weekly to multiple tablets several times daily). Because there is no clear PK/PD target, recommendations lean heavily on package labeling, older PK literature, and retrospective step-down studies. For PCP, dose-limiting toxicity drives treatment failure in up to one-third of patients, which motivates interest in lower-dose strategies.</p>
</div></aside></section>
<section id="possible-role-of-therapeutic-drug-monitoring" class="slide level2 smaller center">
<h2>Possible role of therapeutic drug monitoring</h2>
<p><br></p>
<div class="columns">
<div class="column" style="width:55%;">
<p><strong>Rationale</strong></p>
<ul>
<li>Wide interpatient PK variability</li>
<li>Narrow therapeutic margin at high doses (PCP)</li>
<li>Toxicities are largely <strong>dose/exposure-dependent</strong> (hyperkalemia, marrow suppression, GI, rash)</li>
<li>No consensus PK/PD index → TDM remains investigational</li>
</ul>
</div><div class="column" style="width:45%;">
<p><strong>What is measured</strong></p>
<ul>
<li><strong>Sulfamethoxazole</strong> peak most commonly reported</li>
<li>Historical PCP peak target ~<strong>100–150 µg/mL</strong> (SMX), 1–2 h post-dose <span class="citation" data-cites="Dao2014">(<a href="#/references" role="doc-biblioref" onclick="">Dao et al. 2014</a>)</span></li>
<li>Modern POPPK: SMX peak &gt;100 mg/L &amp; TMP &gt;5 mg/L (efficacy); toxicity above SMX &gt;200, TMP &gt;15 mg/L <span class="citation" data-cites="Leegwater2025">(<a href="#/references" role="doc-biblioref" onclick="">Leegwater et al. 2025</a>)</span></li>
<li>Trimethoprim levels measured less often; assays not widely available</li>
</ul>
</div></div>
<p><strong>Where TDM may help most</strong></p>
<ul>
<li>High-dose/prolonged PCP treatment with poor tolerability</li>
<li>Altered PK: obesity, augmented renal clearance, CRRT/dialysis, critical illness</li>
<li>Difficult pathogens (e.g.&nbsp;<em>Stenotrophomonas</em>) where exposure–response is uncertain</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>TDM for TMP-SMX is <strong>not standardized</strong> — assay access, validated targets, and outcome data are limited. Use alongside clinical response, renal function, potassium, and CBC rather than as a stand-alone endpoint.</p>
</div>
</div>
</div>

<aside><div>
<p>The lack of a validated PK/PD index is the central barrier: without a clear exposure target linked to outcome, TDM cannot yet be applied the way it is for vancomycin or aminoglycosides. Even so, measuring exposure may help individualize therapy in patients at the extremes of PK or those failing to tolerate standard high doses — targeting the lowest effective exposure to preserve efficacy while limiting dose-dependent harm.</p>
</div></aside></section>
<section id="desensitization-protocols" class="slide level2 center">
<h2>Desensitization protocols</h2>
<p><br></p>
<p><strong>When to consider:</strong></p>
<ul>
<li>HIV patients needing PCP prophylaxis</li>
<li>Previous mild-moderate reactions</li>
<li><strong>NOT for SJS/TEN history</strong></li>
</ul>
<p><strong>Rapid 8-hour protocol:</strong></p>
<ul>
<li>Escalating doses hourly</li>
<li>Hospital setting with anaphylaxis capability</li>
<li>Success rate ~70-80%</li>
</ul>

<aside><div>
<p>Desensitization can be life-saving for HIV patients who need PCP prophylaxis but have had prior reactions. It should only be done in a controlled setting by experienced clinicians.</p>
</div></aside></section>
<section id="contraindications" class="slide level2 center">
<h2>Contraindications</h2>
<p><br></p>
<p><strong>Absolute:</strong></p>
<ul>
<li>Known hypersensitivity to sulfonamides or TMP</li>
<li>History of SJS/TEN with sulfonamides</li>
<li>Megaloblastic anemia from folate deficiency</li>
<li>Severe hepatic or renal impairment</li>
<li>Pregnancy at term (&gt;32 weeks)</li>
<li>Infants &lt;2 months (except PCP)</li>
</ul>

<aside><div>
<p>These contraindications should be checked before prescribing. The infant age restriction is due to immature bilirubin metabolism and kernicterus risk.</p>
</div></aside></section>
<section id="monitoring-recommendations" class="slide level2 center">
<h2>Monitoring recommendations</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Timing</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CBC</td>
<td>Baseline, periodically</td>
<td>Cytopenias</td>
</tr>
<tr class="even">
<td>Creatinine</td>
<td>Baseline, week 1</td>
<td>May ↑ from TMP</td>
</tr>
<tr class="odd">
<td>Potassium</td>
<td>Week 1</td>
<td>High-risk patients</td>
</tr>
<tr class="even">
<td>LFTs</td>
<td>If prolonged use</td>
<td>Hepatotoxicity</td>
</tr>
<tr class="odd">
<td>INR</td>
<td>If on warfarin</td>
<td>Interaction</td>
</tr>
</tbody>
</table>

<aside><div>
<p>The extent of monitoring depends on the patient’s risk factors and duration of therapy. Short courses in healthy patients need minimal monitoring; long-term use requires more attention.</p>
</div></aside></section></section>
<section>
<section id="part-10-clinical-cases" class="title-slide slide level1 center" data-background-color="#b20e10">
<h1>PART 10: Clinical Cases</h1>

</section>
<section id="case-1-pcp-prophylaxis" class="slide level2 center">
<h2>Case 1: PCP Prophylaxis</h2>
<p><br></p>
<p><strong>45-year-old man with HIV:</strong></p>
<ul>
<li>CD4 count: 180 cells/µL</li>
<li>No prior opportunistic infections</li>
<li>Taking ART with good adherence</li>
</ul>
<p><strong>Question:</strong> What prophylaxis do you recommend?</p>
</section>
<section id="case-1-answer" class="slide level2 center">
<h2>Case 1: Answer</h2>
<p><br></p>
<p><strong>TMP-SMX 1 DS tablet daily</strong> (or 3x weekly)</p>
<p>Key points:</p>
<ul>
<li>CD4 &lt;200 = indication for PCP prophylaxis</li>
<li>TMP-SMX is first-line</li>
<li>Continue until CD4 &gt;200 for 3+ months on ART</li>
<li>Also provides protection against toxoplasmosis</li>
</ul>

<aside><div>
<p>TMP-SMX prophylaxis can be discontinued once CD4 counts have been &gt;200 for at least 3 months on effective ART. The 3x weekly dosing may be considered if daily dosing causes GI intolerance.</p>
</div></aside></section>
<section id="case-2-uti-in-2025" class="slide level2 center">
<h2>Case 2: UTI in 2025</h2>
<p><br></p>
<p><strong>28-year-old woman with uncomplicated cystitis:</strong></p>
<ul>
<li>Dysuria, frequency × 2 days</li>
<li>No fever</li>
<li>Local E. coli TMP-SMX resistance: 35%</li>
</ul>
<p><strong>Question:</strong> Is TMP-SMX appropriate?</p>
</section>
<section id="case-2-answer" class="slide level2 center">
<h2>Case 2: Answer</h2>
<p><br></p>
<p><strong>No - local resistance too high</strong></p>
<p>Better options:</p>
<ul>
<li>Nitrofurantoin 100 mg BID × 5 days</li>
<li>Fosfomycin 3 g single dose</li>
<li>If fluoroquinolone indicated: short course</li>
</ul>
<p><strong>Rule:</strong> TMP-SMX only if local resistance &lt;20%</p>

<aside><div>
<p>This illustrates why knowing your local antibiogram is essential. TMP-SMX would have been first-line 20 years ago but is no longer appropriate in many areas.</p>
</div></aside></section>
<section id="case-3-hyperkalemia-risk" class="slide level2 center">
<h2>Case 3: Hyperkalemia risk</h2>
<p><br></p>
<p><strong>72-year-old man with cellulitis:</strong></p>
<ul>
<li>History: DM2, CKD (CrCl 35), HTN</li>
<li>Medications: lisinopril, metformin, spironolactone</li>
<li>Started TMP-SMX DS BID for CA-MRSA cellulitis</li>
</ul>
<p><strong>What’s the concern?</strong></p>

<aside><div>
<p>Multiple hyperkalemia risk factors: age, CKD, ACE inhibitor, and potassium-sparing diuretic!</p>
</div></aside></section>
<section id="case-3-answer" class="slide level2 center">
<h2>Case 3: Answer</h2>
<p><br></p>
<p><strong>High hyperkalemia risk!</strong></p>
<p>Risk factors present:</p>
<ul>
<li>Age &gt;65 ✓</li>
<li>CKD (CrCl 35) ✓</li>
<li>ACE inhibitor ✓</li>
<li>Spironolactone ✓</li>
</ul>
<p><strong>Management:</strong></p>
<ul>
<li>Check baseline K+</li>
<li>Recheck in 2-3 days</li>
<li>Consider holding spironolactone during treatment</li>
<li>Alternative antibiotic if K+ &gt;5.5</li>
</ul>

<aside><div>
<p>This patient has essentially every risk factor for TMP-SMX induced hyperkalemia. Close monitoring and potentially holding the spironolactone would be prudent. Some might argue for a different antibiotic choice entirely.</p>
</div></aside></section>
<section id="case-4-the-rash" class="slide level2 center">
<h2>Case 4: The rash</h2>
<p><br></p>
<p><strong>35-year-old HIV+ man on TMP-SMX prophylaxis:</strong></p>
<ul>
<li>Day 10: develops diffuse maculopapular rash</li>
<li>No mucosal involvement</li>
<li>No systemic symptoms</li>
<li>Tolerating oral intake</li>
</ul>
<p><strong>Options?</strong></p>

<aside><div>
<p>This is a common scenario. The key is distinguishing mild reactions that might be managed from severe reactions requiring immediate discontinuation.</p>
</div></aside></section>
<section id="case-4-answer" class="slide level2 center">
<h2>Case 4: Answer</h2>
<p><br></p>
<p><strong>Options to consider:</strong></p>
<ol type="1">
<li><strong>Stop TMP-SMX</strong> and use alternative (dapsone, atovaquone)</li>
<li><strong>Continue with antihistamines</strong> (mild reactions may resolve)</li>
<li><strong>Plan for desensitization</strong> if alternative poorly tolerated</li>
</ol>
<p><strong>Red flags requiring immediate discontinuation:</strong></p>
<ul>
<li>Mucosal involvement</li>
<li>Systemic symptoms</li>
<li>Blistering or desquamation</li>
<li>Fever &gt;38.5°C</li>
</ul>

<aside><div>
<p>Without red flags, some practitioners will continue through mild rashes with symptomatic treatment, as reactions sometimes resolve spontaneously. However, close monitoring is essential.</p>
</div></aside></section>
<section id="case-5-drug-interaction" class="slide level2 center">
<h2>Case 5: Drug interaction</h2>
<p><br></p>
<p><strong>68-year-old woman on warfarin for A-fib:</strong></p>
<ul>
<li>INR therapeutic at 2.5</li>
<li>Started TMP-SMX for UTI</li>
<li>Returns 5 days later with INR 5.8</li>
<li>No bleeding</li>
</ul>
<p><strong>What happened?</strong></p>
</section>
<section id="case-5-answer" class="slide level2 center">
<h2>Case 5: Answer</h2>
<p><br></p>
<p><strong>TMP-SMX inhibits CYP2C9 → ↑ warfarin levels</strong></p>
<p>Management:</p>
<ul>
<li class="fragment">Hold warfarin</li>
<li class="fragment">Vitamin K 1-2 mg PO if significant bleeding risk</li>
<li class="fragment">Recheck INR in 24-48 hours</li>
<li class="fragment">Resume warfarin at reduced dose</li>
<li class="fragment"><strong>Always reduce warfarin when starting TMP-SMX</strong></li>
</ul>

<aside><div>
<p>This interaction is predictable and preventable. Best practice is to empirically reduce warfarin dose by 25-50% when starting TMP-SMX and monitor INR closely.</p>
</div></aside></section></section>
<section>
<section id="summary-and-key-takeaways" class="title-slide slide level1 center" data-background-color="#b20e10">
<h1>Summary and Key Takeaways</h1>

</section>
<section id="key-points-to-remember-12" class="slide level2 center">
<h2>Key Points to Remember (1/2)</h2>
<p><br></p>
<ol type="1">
<li><p><strong>Mechanism:</strong> Sequential blockade of folate synthesis (DHPS + DHFR)</p></li>
<li><p><strong>Synergy:</strong> Combination is bactericidal; components alone are bacteriostatic</p></li>
<li><p><strong>Spectrum:</strong> Broad, but NOT Pseudomonas or anaerobes</p></li>
<li><p><strong>Resistance:</strong> Increasing; always check local patterns for UTIs</p></li>
</ol>
</section>
<section id="key-points-to-remember-22" class="slide level2 center">
<h2>Key Points to Remember (2/2)</h2>
<p><br></p>
<ol start="5" type="1">
<li><p><strong>PCP:</strong> First-line for both treatment and prophylaxis</p></li>
<li><p><strong>Adverse effects:</strong> Higher in HIV; watch for SJS/TEN, hyperkalemia</p></li>
<li><p><strong>Drug interactions:</strong> Warfarin, methotrexate, ACEi/ARBs</p></li>
<li><p><strong>Contraindications:</strong> Late pregnancy, severe renal/hepatic impairment, SJS history</p></li>
<li><p><strong>Dose optimization:</strong> Target the <em>lowest effective</em> TMP dose; emerging data support lower-dose PCP, and TDM (SMX peak) may help individualize therapy at PK extremes</p></li>
</ol>

<aside><div>
<p>Clinical application requires awareness of adverse effects and interactions. TMP-SMX remains valuable but must be used thoughtfully. The lowest-effective-dose principle and cautious use of TDM are increasingly relevant given dose-dependent toxicity.</p>
</div></aside></section>
<section id="when-to-choose-tmp-smx" class="slide level2 center">
<h2>When to Choose TMP-SMX</h2>
<p><br></p>
<p><strong>Excellent choice for:</strong></p>
<ul>
<li>PCP (treatment and prophylaxis)</li>
<li>Nocardiosis</li>
<li>Stenotrophomonas</li>
<li>CA-MRSA skin infections</li>
<li>UTIs (if local susceptibility high)</li>
</ul>
<p><strong>Think twice if:</strong></p>
<ul>
<li>High local resistance</li>
<li>Multiple hyperkalemia risk factors</li>
<li>Drug interactions (warfarin, MTX)</li>
<li>Late pregnancy</li>
</ul>
</section>
<section id="references" class="slide level2 smaller scrollable">
<h2>References</h2>
<p><br></p>

<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-ButlerLaporte2020" class="csl-entry" role="listitem">
Butler-Laporte, Guillaume, Elizabeth Smyth, Alexandre Amar-Zifkin, Matthew P. Cheng, Emily G. McDonald, and Todd C. Lee. 2020. <span>“Low-Dose Trimethoprim-Sulfamethoxazole for the Treatment of <span class="nocase">Pneumocystis jirovecii</span> Pneumonia: A Systematic Review and Meta-Analysis.”</span> <em>Open Forum Infectious Diseases</em> 7 (5): ofaa112. <a href="https://doi.org/10.1093/ofid/ofaa112">https://doi.org/10.1093/ofid/ofaa112</a>.
</div>
<div id="ref-Dao2014" class="csl-entry" role="listitem">
Dao, Betsy D., Jason N. Barreto, Robert C. Wolf, Ross A. Dierkhising, Matthew F. Plevak, and Pritish K. Tosh. 2014. <span>“Serum Peak Sulfamethoxazole Concentrations Demonstrate Difficulty in Achieving a Target Range: A Retrospective Cohort Study.”</span> <em>Current Therapeutic Research</em> 76: 104–9. <a href="https://doi.org/10.1016/j.curtheres.2014.08.003">https://doi.org/10.1016/j.curtheres.2014.08.003</a>.
</div>
<div id="ref-Lasko2022" class="csl-entry" role="listitem">
Lasko, Maxwell J., Matthew L. Gethers, Jennifer L. Tabor-Rennie, David P. Nicolau, and Joseph L. Kuti. 2022. <span>“In Vitro Time-Kill and Pharmacodynamics of Trimethoprim-Sulfamethoxazole Against <span class="nocase">Stenotrophomonas maltophilia</span>.”</span> <em>Antimicrobial Agents and Chemotherapy</em> 66 (2): e0158321. <a href="https://doi.org/10.1128/AAC.01583-21">https://doi.org/10.1128/AAC.01583-21</a>.
</div>
<div id="ref-Leegwater2025" class="csl-entry" role="listitem">
Leegwater, Emiel, Lauren Baidjoe, Erik B. Wilms, et al. 2025. <span>“Population Pharmacokinetics of Trimethoprim/Sulfamethoxazole: Dosage Optimization for Patients with Renal Insufficiency or Receiving Continuous Renal Replacement Therapy.”</span> <em>Clinical Pharmacology and Therapeutics</em> 117 (1): 184–92. <a href="https://doi.org/10.1002/cpt.3421">https://doi.org/10.1002/cpt.3421</a>.
</div>
<div id="ref-Tamma2024" class="csl-entry" role="listitem">
Tamma, Pranita D., Emily L. Heil, Julie Ann Justo, Amy J. Mathers, Michael J. Satlin, and Robert A. Bonomo. 2024. <span>“Infectious Diseases Society of America 2024 Guidance on the Treatment of Antimicrobial-Resistant Gram-Negative Infections.”</span> <em>Clinical Infectious Diseases</em>, ciae403. <a href="https://doi.org/10.1093/cid/ciae403">https://doi.org/10.1093/cid/ciae403</a>.
</div>
</div>
</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="chapter-slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="chapter-slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="chapter-slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="chapter-slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="chapter-slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="chapter-slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="chapter-slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="chapter-slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="chapter-slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="chapter-slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
    (function() {
      let previousOnload = window.onload;
      window.onload = () => {
        if (previousOnload) {
          previousOnload();
        }
        lightboxQuarto.on('slide_before_load', (data) => {
          const { slideIndex, slideNode, slideConfig, player, trigger } = data;
          const href = trigger.getAttribute('href');
          if (href !== null) {
            const imgEl = window.document.querySelector(`a[href="${href}"] img`);
            if (imgEl !== null) {
              const srcAttr = imgEl.getAttribute("src");
              if (srcAttr && srcAttr.startsWith("data:")) {
                slideConfig.href = srcAttr;
              }
            }
          } 
        });
      
        lightboxQuarto.on('slide_after_load', (data) => {
          const { slideIndex, slideNode, slideConfig, player, trigger } = data;
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(slideNode);
          }
        });
      
      };
      
    })();
              </script>
    

</body></html>